# System Message Types
MSG_REGISTER = "REGISTER"
MSG_REGISTER_ACK = "REGISTER_ACK"
MSG_PING = "PING"
MSG_PONG = "PONG"
MSG_SHUTDOWN = "SHUTDOWN"
MSG_LOG = "LOG"

# Application Message Types
MSG_SUNBOX_COMMAND = "SUNBOX_COMMAND"
MSG_SUNBOX_RESPONSE = "SUNBOX_RESPONSE"
MSG_SUNBOX_STATUS = "SUNBOX_STATUS"

# Template and Status Message Types
MSG_STATUS_UPDATE = "STATUS_UPDATE"
MSG_CUSTOM_COMMAND = "CUSTOM_COMMAND"
MSG_CUSTOM_RESPONSE = "CUSTOM_RESPONSE"

# Add additional message types as needed
MSG_SHUTDOWN_ACK = "SHUTDOWN_ACK"
