# System Message Types
MSG_REGISTER = "REGISTER"
MSG_REGISTER_ACK = "REGISTER_ACK"
MSG_PING = "PING"
MSG_PONG = "PONG"
MSG_SHUTDOWN = "SHUTDOWN"
MSG_LOG = "LOG"

# Application Message Types
MSG_SUNBOX_COMMAND = "SUNBOX_COMMAND"
MSG_SUNBOX_RESPONSE = "SUNBOX_RESPONSE"
MSG_SUNBOX_STATUS = "SUNBOX_STATUS"

# Add additional message types as needed
