# Port Configuration
AUTH_PORT = 2828
CONTROL_PANEL_PORT = 2828  # Same as auth since they run sequentially
ZEROMQ_PORT = 5555

# Application Settings
MAX_REGISTRATION_ATTEMPTS = 30
REGISTRATION_RETRY_INTERVAL = 2
PING_INTERVAL = 5
PING_TIMEOUT = 15
MAX_MESSAGE_HISTORY = 1000

# Logging Settings
LOG_TO_DESKTOP_ON_CRASH = True
MAX_LOG_MESSAGES = 1000
